config/routes.rb
Rails.application.routes.draw do

  resources :users do
     resources :tweets
  end
  root "users#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :user_id, :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
  validates :name, :img_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_user
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweet = Tweet.where(user: @user) #@tweet va récupérer la liste des tweet qui ont le bon user_id

  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @tweet.user = @user
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = @user
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to user_path(@user), notice: 'Tweet was successfully created.' }
        logger.info @tweet
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to user_tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_user
      @user  = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:id, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :img_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twittodon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for([@user, @tweet]) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', user_tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<nav>
  <div class="nav-wrapper">
    <%=link_to root_path do %>
      <span class="brand-logo center">Twittodon</span>
    <%end %>
  </div>
</nav>



<div class="bodyPad">
<h1>Tweets de <%=@user.name  %></h1>

<table>
  <thead>
    <tr>
      <th>Identifiant du Tweet</th>
      <th>Contenu du tweet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweet.each do |tweet| %>
      <tr>
        <td><%= tweet.id %></td>
        <td><%= tweet.content %></td>
        <td><%= link_to 'Supprimer le tweet', user_tweet_path(id: tweet.id), method: :delete, data: { confirm: 'Êtes vous sur?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau tweet', new_user_tweet_path %>
</div>

app/views/tweets/new.html.erb
<p id="notice"><%= notice %></p>
<nav>
  <div class="nav-wrapper">
    <%=link_to root_path do %>
      <span class="brand-logo center">Twittodon</span>
    <%end %>
  </div>
</nav>
<div class="bodyPad">
<h1>Nouveau tweet</h1>

<%= render 'form' %>

<br>
<%= link_to 'Retour', user_tweets_path %>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<nav>
  <div class="nav-wrapper">
    <%=link_to root_path do %>
      <span class="brand-logo center">Twittodon</span>
    <%end %>
  </div>
</nav>
<div class="bodyPad">
<p>
  <strong>Identifiant du tweet:</strong>
  <%= @tweet.id %>
</p>

<p>
  <strong>Contenu du tweet:</strong>
  <%= @tweet.content %>
</p>

<%= link_to 'Editer', edit_user_tweet_path(@tweet) %> |
<%= link_to 'Retour', user_tweets_path %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<p id="notice"><%= notice %></p>
<nav>
  <div class="nav-wrapper">
    <%=link_to root_path do %>
      <span class="brand-logo center">Twittodon</span>
    <%end %>
  </div>
</nav>
<div class="bodyPad">
<h1>Edition de <%=@user.name %></h1>

<%= render 'form' %>
<br>
<%= link_to 'Voir l\'utilisateur', @user %> |
<%= link_to 'Retour', users_path %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<nav>
  <div class="nav-wrapper">
    <%=link_to root_path do %>
      <span class="brand-logo center">Twittodon</span>
    <%end %>
  </div>
</nav>

<div class="bodyPad">

<h2>Utilisateurs</h2>


<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Image de profil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%=link_to  user do%><img width="300" src="<%= user.img_url %>"><%end %></td>
        <td><%= link_to 'Afficher l\'utilisateur', user %></td>
        <td><%= link_to 'Editer l\'utilisateur', edit_user_path(user) %></td>
        <td><%= link_to 'Supprimer l\'utilisateur', user, method: :delete, data: { confirm: 'Êtes vous sur?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'Créer un utilisateur', new_user_path %>

</div>

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>
<nav>
  <div class="nav-wrapper">
    <%=link_to root_path do %>
      <span class="brand-logo center">Twittodon</span>
    <%end %>
  </div>
</nav>
<div class="bodyPad">
<h1>Nouvel utilisateur</h1>

<%= render 'form' %>
<br>
<%= link_to 'Retour', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<nav>
  <div class="nav-wrapper">
    <%=link_to root_path do %>
      <span class="brand-logo center">Twittodon</span>
    <%end %>
  </div>
</nav>

<div class="bodyPad">


<p>
  <h1>
  <%= @user.name %>
  </h1>
</p>

<p>

  <img alt="<%= @user.img_url %>" width="350" src="<%= @user.img_url %>">
</p>
<br/>
<br/>

<p>
  <strong><%= link_to 'Voir les tweets', user_tweets_path(@user)%></strong>
</p>

<%= link_to 'Editer', edit_user_path(@user) %> |
<%= link_to 'Retour', users_path %>

</div>